# fly.toml file generated for feedreader-redis on 2022-08-14T19:53:50+01:00

app = "feedreader-redis"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/redis:6.2.6"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
