app = "feedreader-celerybeat"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  HOSTNAME = "feedreader-celerybeat.fly.dev"

[build]
  build-target = "prod"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = ["celery", "-A", "feedreader", "beat", "-l", "info"]
