app = "feedreader-scrapers"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  HOSTNAME = "feedreader-scrapers.fly.dev"

[build]
  build-target = "prod"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = ["celery", "-A", "feedreader", "worker", "-l", "info", "-n", "scraper@%h", "-Q", "feeds"]
