app = "feedreader"
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
  web = "gunicorn -b 0.0.0.0:8000 --workers 2 feedreader.wsgi"
  beat = "celery -A feedreader beat -l INFO"

[env]
  HOSTNAME = "feedreader.fly.dev"

[build]
  build-target = "prod"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  processes = ["web"]
  internal_port = 8000
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"

[deploy]
  release_command = "sh release.sh"
