# fly.toml file generated for feedreader on 2022-08-28T19:38:07+01:00

app = "feedreader"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  HOSTNAME = "feedreader.fly.dev"
  AWS_S3_REGION_NAME = "ams3"
  AWS_STORAGE_BUCKET_NAME = "feedreader"
  AWS_S3_ENDPOINT_URL = 'https://ams3.digitaloceanspaces.com'


[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"


[mounts]
source="db"
destination="/data"
